### ISSUE TITLE
This project is alive?

### ISSUE THREAD

**Issue by Enuvid** [LeetCode-OpenSource/rxjs-hooks#534]
Unfortunately i don't see any activity here :(

@Brooooooklyn @zry656565

**Comment by Brooooooklyn** [comment]
I was removed from the Github organization after I left LeetCode a year ago, so I didn't receive any notifications from Github during that time until this comment from you.

Besides this, I think this project is in maintain mode now, because @zry656565 is also leaving LeetCode now, nobody can maintain this repo anymore.

**Comment by eshturman** [comment]
Is this LeetCode property? I mean, can we move that project into separate organization and continue support project with comunity?

@Brooooooklyn

**Comment by dennisroche** [comment]
Perhaps time to fork the library so that it can be continued to be maintained.

**Comment by kaladivo** [comment]
There already is [observable-hooks](https://github.com/crimx/observable-hooks) library. Seems to be much better maintained and even has more downloads at npm.
